package graphic;

import core.Point;

public abstract class ExamTranslateAbstractPanel extends AbstractPanel {
    /**
     * Creates new form ExamTranslateAbstractPanel
     */
    public ExamTranslateAbstractPanel() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        answerInput = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        rightAnsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rightAnsLabel = new javax.swing.JLabel();
        resLabel = new javax.swing.JLabel();
        wordLabel = new javax.swing.JLabel();

        setForeground(java.awt.Color.black);

        jLabel1.setBackground(java.awt.Color.white);
        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Please enter your answer");

        answerInput.setBackground(java.awt.Color.white);
        answerInput.setForeground(java.awt.Color.black);
        answerInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerInputActionPerformed(evt);
            }
        });

        submitButton.setBackground(java.awt.Color.white);
        submitButton.setForeground(java.awt.Color.black);
        submitButton.setText("Submit");
        submitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        submitButton.setContentAreaFilled(false);
        submitButton.setOpaque(true);
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonPress(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonHighlight(evt);
            }
        });
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        rightAnsPanel.setForeground(java.awt.Color.black);

        jLabel2.setBackground(java.awt.Color.white);
        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Right Answer :");

        rightAnsLabel.setBackground(java.awt.Color.white);
        rightAnsLabel.setForeground(java.awt.Color.black);

        javax.swing.GroupLayout rightAnsPanelLayout = new javax.swing.GroupLayout(rightAnsPanel);
        rightAnsPanel.setLayout(rightAnsPanelLayout);
        rightAnsPanelLayout.setHorizontalGroup(
            rightAnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightAnsPanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightAnsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addContainerGap())
        );
        rightAnsPanelLayout.setVerticalGroup(
            rightAnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightAnsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rightAnsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rightAnsLabel))
                .addContainerGap())
        );

        resLabel.setBackground(java.awt.Color.white);
        resLabel.setForeground(java.awt.Color.black);

        wordLabel.setBackground(java.awt.Color.white);
        wordLabel.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        wordLabel.setForeground(java.awt.Color.black);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(answerInput, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(wordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(resLabel)))
                .addContainerGap(86, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(rightAnsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answerInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(rightAnsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(resLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void answerInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerInputActionPerformed

    private void buttonPress(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPress
        SwingUtil.buttonClick(evt);
    }//GEN-LAST:event_buttonPress

    private void buttonHighlight(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHighlight
        SwingUtil.buttonRelease(evt);
    }//GEN-LAST:event_buttonHighlight

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        rightAnsPanel.setVisible(true);
        answerInput.setEditable(false);
        submitButton.setEnabled(false);
        if (answerInput.getText().trim().toLowerCase().equals(rightAnsLabel.getText())) {
            resLabel.setText(SwingUtil.rightAnsStr);
            answerInput.setBackground(java.awt.Color.GREEN);
            Point.getInstance().increasePoint();
        } else {
            resLabel.setText(SwingUtil.wrongAnsStr);
            answerInput.setBackground(java.awt.Color.RED);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    @Override
    public abstract void loadQuestion();
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField answerInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    protected javax.swing.JLabel resLabel;
    protected javax.swing.JLabel rightAnsLabel;
    protected javax.swing.JPanel rightAnsPanel;
    protected javax.swing.JButton submitButton;
    protected javax.swing.JLabel wordLabel;
    // End of variables declaration//GEN-END:variables
}
