package graphic;

import core.Vocabulary;
import java.io.File;
import java.util.ArrayList;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class ManagerPanel extends javax.swing.JPanel {
    private int curVocIndex;
    /**
     * Creates new form ManagerPanel
     */
    public ManagerPanel() {
        SwingUtil.setUIFont(SwingUtil.defaultFont);
        initComponents();
        additionInit();
    }
    
    private void additionInit() {
        updateListVoc();
        vocManPanel.setVisible(false);
        
        delWord.setUI(new javax.swing.plaf.basic.BasicComboBoxUI() {
            @Override
            protected javax.swing.JButton createArrowButton() {
                return new javax.swing.JButton() {
                    @Override
                    public int getWidth() {
                        return 0;
                    }
                };
            }
        });
    
        addButton.setIcon(new javax.swing.ImageIcon("icon/icons8-plus-20.png"));
        renameButton.setIcon(new javax.swing.ImageIcon("icon/icons8-rename-20.png"));
        delButton.setIcon(new javax.swing.ImageIcon("icon/icons8-clear-symbol-20.png"));
        addWButton.setIcon(new javax.swing.ImageIcon("icon/icons8-plus-20.png"));
        delWButton.setIcon(new javax.swing.ImageIcon("icon/icons8-clear-symbol-20.png"));
        mergeButton.setIcon(new javax.swing.ImageIcon("icon/icons8-merge-20.png"));
        importButton.setIcon(new javax.swing.ImageIcon("icon/icons8-microsoft-excel-20.png"));
        exportButton.setIcon(new javax.swing.ImageIcon("icon/icons8-microsoft-excel-20.png"));
    }
    
    private void updateListVoc() {
        listVoc.setListData(SwingUtil.dict.vMng.listVocabulary());
    }
    
    private void updateVocInfo() {
        if (curVocIndex == -1) {
            nameLabel.setText("");
            nWordsLabel.setText("");
            importLabel.setText("");
        }
        else {
            ArrayList<String> vocInfo = SwingUtil.dict.vMng.vocAt(curVocIndex).getInfo();
            nameLabel.setText(vocInfo.get(0));
            nWordsLabel.setText(vocInfo.get(1));
            importLabel.setText(vocInfo.get(2));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        getNameDialog = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        addWordDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        wordInput = new javax.swing.JTextField();
        pronunInput = new javax.swing.JTextField();
        meanInput = new javax.swing.JTextField();
        okButton1 = new javax.swing.JButton();
        delWDialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        okButton2 = new javax.swing.JButton();
        delWord = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listVoc = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nWordsLabel = new javax.swing.JLabel();
        importLabel = new javax.swing.JLabel();
        vocManPanel = new javax.swing.JPanel();
        renameButton = new javax.swing.JButton();
        addWButton = new javax.swing.JButton();
        delWButton = new javax.swing.JButton();
        mergeButton = new javax.swing.JButton();
        importButton = new javax.swing.JButton();
        exportButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();

        getNameDialog.setTitle("Rename");
        getNameDialog.setBounds(new java.awt.Rectangle(300, 200, 380, 160));
        getNameDialog.setResizable(false);

        jPanel2.setForeground(java.awt.Color.black);

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Please enter name (topic) of vocabulary");

        inputName.setBackground(java.awt.Color.white);
        inputName.setForeground(java.awt.Color.black);
        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });

        okButton.setBackground(java.awt.Color.white);
        okButton.setForeground(java.awt.Color.black);
        okButton.setText("OK");
        okButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        okButton.setContentAreaFilled(false);
        okButton.setOpaque(true);
        okButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonClick(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRelease(evt);
            }
        });
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout getNameDialogLayout = new javax.swing.GroupLayout(getNameDialog.getContentPane());
        getNameDialog.getContentPane().setLayout(getNameDialogLayout);
        getNameDialogLayout.setHorizontalGroup(
            getNameDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        getNameDialogLayout.setVerticalGroup(
            getNameDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(getNameDialogLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        addWordDialog.setTitle("Add Word");
        addWordDialog.setBounds(new java.awt.Rectangle(300, 200, 433, 250));
        addWordDialog.setResizable(false);

        jPanel1.setForeground(java.awt.Color.black);

        jLabel4.setBackground(java.awt.Color.white);
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Please enter word, pronunciation and mean:");

        jLabel5.setBackground(java.awt.Color.white);
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("Word");

        jLabel9.setBackground(java.awt.Color.white);
        jLabel9.setForeground(java.awt.Color.black);
        jLabel9.setText("Pronunciation");

        jLabel10.setBackground(java.awt.Color.white);
        jLabel10.setForeground(java.awt.Color.black);
        jLabel10.setText("Mean");

        wordInput.setBackground(java.awt.Color.white);
        wordInput.setForeground(java.awt.Color.black);

        pronunInput.setBackground(java.awt.Color.white);
        pronunInput.setForeground(java.awt.Color.black);

        meanInput.setBackground(java.awt.Color.white);
        meanInput.setForeground(java.awt.Color.black);

        okButton1.setBackground(java.awt.Color.white);
        okButton1.setForeground(java.awt.Color.black);
        okButton1.setText("OK");
        okButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        okButton1.setContentAreaFilled(false);
        okButton1.setOpaque(true);
        okButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonClick(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRelease(evt);
            }
        });
        okButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(wordInput)
                            .addComponent(pronunInput)
                            .addComponent(meanInput, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(okButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(wordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pronunInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(meanInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(okButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout addWordDialogLayout = new javax.swing.GroupLayout(addWordDialog.getContentPane());
        addWordDialog.getContentPane().setLayout(addWordDialogLayout);
        addWordDialogLayout.setHorizontalGroup(
            addWordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        addWordDialogLayout.setVerticalGroup(
            addWordDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        delWDialog.setTitle("Delete Word");
        delWDialog.setBounds(new java.awt.Rectangle(300, 200, 343, 175));
        delWDialog.setResizable(false);

        jPanel3.setForeground(java.awt.Color.black);

        jLabel12.setBackground(java.awt.Color.white);
        jLabel12.setForeground(java.awt.Color.black);
        jLabel12.setText("Please enter word");

        okButton2.setBackground(java.awt.Color.white);
        okButton2.setForeground(java.awt.Color.black);
        okButton2.setText("OK");
        okButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        okButton2.setContentAreaFilled(false);
        okButton2.setOpaque(true);
        okButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonClick(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRelease(evt);
            }
        });
        okButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButton2ActionPerformed(evt);
            }
        });

        delWord.setBackground(java.awt.Color.white);
        delWord.setEditable(true);
        delWord.setForeground(java.awt.Color.black);
        delWord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(delWord, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(okButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(delWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout delWDialogLayout = new javax.swing.GroupLayout(delWDialog.getContentPane());
        delWDialog.getContentPane().setLayout(delWDialogLayout);
        delWDialogLayout.setHorizontalGroup(
            delWDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        delWDialogLayout.setVerticalGroup(
            delWDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setForeground(java.awt.Color.black);

        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Vocabulary order");

        jScrollPane1.setForeground(java.awt.Color.black);

        listVoc.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                changeCurVoc(evt);
            }
        });
        jScrollPane1.setViewportView(listVoc);

        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Vocabulary infomation");

        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Name (Topic)");

        jLabel7.setForeground(java.awt.Color.black);
        jLabel7.setText("Total words");

        jLabel8.setForeground(java.awt.Color.black);
        jLabel8.setText("Import from");

        nameLabel.setForeground(java.awt.Color.black);

        nWordsLabel.setForeground(java.awt.Color.black);

        importLabel.setForeground(java.awt.Color.black);

        renameButton.setBackground(java.awt.Color.white);
        renameButton.setForeground(java.awt.Color.black);
        renameButton.setText("  Rename  ");
        renameButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        renameButton.setContentAreaFilled(false);
        renameButton.setOpaque(true);
        renameButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonClick(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRelease(evt);
            }
        });
        renameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameButtonActionPerformed(evt);
            }
        });

        addWButton.setBackground(java.awt.Color.white);
        addWButton.setForeground(java.awt.Color.black);
        addWButton.setText(" Add Word ");
        addWButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addWButton.setContentAreaFilled(false);
        addWButton.setOpaque(true);
        addWButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonClick(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRelease(evt);
            }
        });
        addWButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addWButtonActionPerformed(evt);
            }
        });

        delWButton.setBackground(java.awt.Color.white);
        delWButton.setForeground(java.awt.Color.black);
        delWButton.setText("Delete word");
        delWButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        delWButton.setContentAreaFilled(false);
        delWButton.setOpaque(true);
        delWButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonClick(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRelease(evt);
            }
        });
        delWButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delWButtonActionPerformed(evt);
            }
        });

        mergeButton.setBackground(java.awt.Color.white);
        mergeButton.setForeground(java.awt.Color.black);
        mergeButton.setText("  Merge   ");
        mergeButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mergeButton.setContentAreaFilled(false);
        mergeButton.setOpaque(true);
        mergeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonClick(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRelease(evt);
            }
        });
        mergeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mergeButtonActionPerformed(evt);
            }
        });

        importButton.setBackground(java.awt.Color.white);
        importButton.setForeground(java.awt.Color.black);
        importButton.setText("  Import  ");
        importButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        importButton.setContentAreaFilled(false);
        importButton.setOpaque(true);
        importButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonClick(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRelease(evt);
            }
        });
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        exportButton.setBackground(java.awt.Color.white);
        exportButton.setForeground(java.awt.Color.black);
        exportButton.setText("  Export  ");
        exportButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        exportButton.setContentAreaFilled(false);
        exportButton.setOpaque(true);
        exportButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonClick(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRelease(evt);
            }
        });
        exportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportButtonActionPerformed(evt);
            }
        });

        delButton.setBackground(java.awt.Color.white);
        delButton.setForeground(java.awt.Color.black);
        delButton.setText("  Delete  ");
        delButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        delButton.setContentAreaFilled(false);
        delButton.setOpaque(true);
        delButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonClick(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRelease(evt);
            }
        });
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout vocManPanelLayout = new javax.swing.GroupLayout(vocManPanel);
        vocManPanel.setLayout(vocManPanelLayout);
        vocManPanelLayout.setHorizontalGroup(
            vocManPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(delWButton, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
            .addComponent(addWButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(delButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(renameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mergeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(importButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(exportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        vocManPanelLayout.setVerticalGroup(
            vocManPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vocManPanelLayout.createSequentialGroup()
                .addComponent(renameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addWButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delWButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mergeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(importButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addButton.setBackground(java.awt.Color.white);
        addButton.setForeground(java.awt.Color.black);
        addButton.setText("Add");
        addButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addButton.setContentAreaFilled(false);
        addButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        addButton.setOpaque(true);
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonClick(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRelease(evt);
            }
        });
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(vocManPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nWordsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(importLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(nameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(nWordsLabel)))
                    .addComponent(vocManPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(importLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8))
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void delWButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delWButtonActionPerformed
        for (String s: SwingUtil.dict.vMng.vocAt(curVocIndex).getKeyword())
            delWord.addItem(s);
        delWord.setSelectedIndex(-1);
        AutoCompleteDecorator.decorate(delWord);
        delWDialog.setVisible(true);
    }//GEN-LAST:event_delWButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        SwingUtil.dict.vMng.removeVocabulary(curVocIndex);
        int newChosen = curVocIndex;
        if (curVocIndex == SwingUtil.dict.vMng.size())
            newChosen--;
        updateListVoc();
        listVoc.setSelectedIndex(newChosen);
        updateVocInfo();
    }//GEN-LAST:event_delButtonActionPerformed

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        javax.swing.JFileChooser importWindow = new javax.swing.JFileChooser();
        importWindow.setCurrentDirectory(new File("/home/darkness"));
        importWindow.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Microsoft Excel 97 - 2003 (*.xls)", "xls"));
        importWindow.setDialogTitle("Import data");
        importWindow.showOpenDialog(null);
        
        File selectFile = importWindow.getSelectedFile();
        if (selectFile != null) {
            SwingUtil.dict.vMng.vocAt(curVocIndex).loadFromFile(selectFile.getPath());
            int tmp = curVocIndex;
            updateListVoc();
            listVoc.setSelectedIndex(tmp);
            updateVocInfo();
            javax.swing.JOptionPane.showMessageDialog(this, "Import data successfully");
        }
    }//GEN-LAST:event_importButtonActionPerformed

    private void renameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameButtonActionPerformed
        inputName.setText("");
        getNameDialog.setVisible(true);
    }//GEN-LAST:event_renameButtonActionPerformed

    private void buttonClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClick
        SwingUtil.buttonClick(evt);
    }//GEN-LAST:event_buttonClick

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        SwingUtil.dict.vMng.addVocabulary();
        updateListVoc();
        listVoc.setSelectedIndex(listVoc.getLastVisibleIndex());
        updateVocInfo();
    }//GEN-LAST:event_addButtonActionPerformed

    private void buttonRelease(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRelease
        SwingUtil.buttonRelease(evt);
    }//GEN-LAST:event_buttonRelease

    private void changeCurVoc(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_changeCurVoc
        curVocIndex = listVoc.getSelectedIndex();
        if (curVocIndex != -1)
            vocManPanel.setVisible(true);
        else
            vocManPanel.setVisible(false);
        updateVocInfo();
    }//GEN-LAST:event_changeCurVoc

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
            String name = inputName.getText();
            if (name.length() != 0) {
                SwingUtil.dict.vMng.vocAt(curVocIndex).setName(name);
                int tmp = curVocIndex;
                updateListVoc();
                listVoc.setSelectedIndex(tmp);
                updateVocInfo();
                getNameDialog.dispose();
                return;
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Empty name is not legal", "Error message", javax.swing.JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_okButtonActionPerformed

    private void addWButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addWButtonActionPerformed
        wordInput.setText("");
        pronunInput.setText("");
        meanInput.setText("");
        addWordDialog.setVisible(true);
    }//GEN-LAST:event_addWButtonActionPerformed

    private void okButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButton1ActionPerformed
        String word = wordInput.getText();
        String pronun = pronunInput.getText();
        String mean = meanInput.getText();
        if (word.length() * pronun.length() * mean.length() != 0) {
            SwingUtil.dict.vMng.vocAt(curVocIndex).addWord(word, mean, pronun);
            updateVocInfo();
            addWordDialog.dispose();
            javax.swing.JOptionPane.showMessageDialog(this, "Add word sucessfully");
        } else 
            javax.swing.JOptionPane.showMessageDialog(this, "Name, Pronunciation and Mean is not empty", "Error message", javax.swing.JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_okButton1ActionPerformed

    private void okButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButton2ActionPerformed
        String key = (String)delWord.getSelectedItem();
        if (key.length() == 0 || SwingUtil.dict.vMng.vocAt(curVocIndex).deleteWord(key) == 404)
            javax.swing.JOptionPane.showMessageDialog(this, "Word not found", "Error message", javax.swing.JOptionPane.ERROR_MESSAGE);
        else {
            updateVocInfo();
            delWDialog.dispose();
            javax.swing.JOptionPane.showMessageDialog(this, "Delete word sucessfully");
        }
    }//GEN-LAST:event_okButton2ActionPerformed

    private void mergeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mergeButtonActionPerformed
        int[] listIndices = listVoc.getSelectedIndices();
        if (listIndices.length == 2) {
            int srcIndex = listVoc.getLeadSelectionIndex();
            int dstIndex = listIndices[0] + listIndices[1] - srcIndex;            
            Vocabulary src = SwingUtil.dict.vMng.vocAt(srcIndex);
            Vocabulary dst = SwingUtil.dict.vMng.vocAt(dstIndex);
            dst.merge(src);
            curVocIndex = srcIndex;
            delButtonActionPerformed(null);
            listVoc.setSelectedIndex(dstIndex);
            updateVocInfo();
            String msg = String.format("Merge %s to %s successfully", src.getName().toUpperCase(), dst.getName().toUpperCase());
            javax.swing.JOptionPane.showMessageDialog(this, msg);
        }
    }//GEN-LAST:event_mergeButtonActionPerformed

    private void exportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportButtonActionPerformed
        javax.swing.JFileChooser exportWindow = new javax.swing.JFileChooser();
        exportWindow.setCurrentDirectory(new File("/home/darkness"));
        exportWindow.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Microsoft Excel 97 - 2003 (*.xls)", "xls"));
//        exportWindow.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        exportWindow.setDialogTitle("Export data");
        exportWindow.showOpenDialog(null);
        
        File selectFile = exportWindow.getSelectedFile();
        if (selectFile != null) {
            String path = selectFile.getPath() + ".xls";
            SwingUtil.dict.vMng.vocAt(curVocIndex).writeToFile(path);
            int tmp = curVocIndex;
            updateListVoc();
            listVoc.setSelectedIndex(tmp);
            updateVocInfo();
            javax.swing.JOptionPane.showMessageDialog(this, "Export data successfully");
        }
    }//GEN-LAST:event_exportButtonActionPerformed

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addWButton;
    private javax.swing.JDialog addWordDialog;
    private javax.swing.JButton delButton;
    private javax.swing.JButton delWButton;
    private javax.swing.JDialog delWDialog;
    private javax.swing.JComboBox<String> delWord;
    private javax.swing.JButton exportButton;
    private javax.swing.JDialog getNameDialog;
    private javax.swing.JButton importButton;
    private javax.swing.JLabel importLabel;
    private javax.swing.JTextField inputName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listVoc;
    private javax.swing.JTextField meanInput;
    private javax.swing.JButton mergeButton;
    private javax.swing.JLabel nWordsLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JButton okButton1;
    private javax.swing.JButton okButton2;
    private javax.swing.JTextField pronunInput;
    private javax.swing.JButton renameButton;
    private javax.swing.JPanel vocManPanel;
    private javax.swing.JTextField wordInput;
    // End of variables declaration//GEN-END:variables
}
