package graphic;

import core.Point;
import java.util.ArrayList;

public class RevisePanel extends javax.swing.JPanel {
    private int nQuestions, curQues;
    private ArrayList<AbstractPanel> listFormatTest;
    private int[] choosen = new int[6];
    private ArrayList<javax.swing.JCheckBox> listCheckBox;
    /**
     * Creates new form RevisePanel
     */
    public RevisePanel() {
        initComponents();
        addtionInit();
    }
    
    private void addtionInit() {
        listCheckBox = new ArrayList<>();
        listCheckBox.add(jCheckBox1);
        listCheckBox.add(jCheckBox2);
        listCheckBox.add(jCheckBox3);
        listCheckBox.add(jCheckBox4);
        listCheckBox.add(jCheckBox5);
        listCheckBox.add(jCheckBox6);
        listFormatTest = new ArrayList<>();
        listFormatTest.add(testEngViePanel);
        listFormatTest.add(testVieEngPanel);
        listFormatTest.add(testPronunViePanel);
        listFormatTest.add(testViePronunPanel);
        listFormatTest.add(examTranslateVieEngPanel);
        listFormatTest.add(examTranslatePronunEngPanel);
        
        nextButton.setIcon(new javax.swing.ImageIcon("icon/icons8-next-page-20.png"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentPanel0 = new javax.swing.JPanel();
        startPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nQuesInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        processPanel = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        progressLabel = new javax.swing.JLabel();
        parentPanel1 = new javax.swing.JPanel();
        testEngViePanel = new graphic.TestEngViePanel();
        testVieEngPanel = new graphic.TestVieEngPanel();
        testPronunViePanel = new graphic.TestPronunViePanel();
        testViePronunPanel = new graphic.TestViePronunPanel();
        examTranslateVieEngPanel = new graphic.ExamTranslateVieEngPanel();
        examTranslatePronunEngPanel = new graphic.ExamTranslatePronunEngPanel();
        nextButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        curQuesLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(java.awt.Color.white);
        setForeground(java.awt.Color.black);

        parentPanel0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        parentPanel0.setForeground(java.awt.Color.black);
        parentPanel0.setLayout(new java.awt.CardLayout());

        startPanel.setForeground(java.awt.Color.black);

        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Please Choice:");

        startButton.setBackground(java.awt.Color.white);
        startButton.setForeground(java.awt.Color.black);
        startButton.setText("Start");
        startButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        startButton.setContentAreaFilled(false);
        startButton.setOpaque(true);
        startButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonPress(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRelease(evt);
            }
        });
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        jLabel2.setForeground(java.awt.Color.black);
        jLabel2.setText("Number of questions");

        nQuesInput.setBackground(java.awt.Color.white);
        nQuesInput.setForeground(java.awt.Color.black);
        nQuesInput.setText("10");
        nQuesInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nQuesInputActionPerformed(evt);
            }
        });

        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("Format of questions");

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(java.awt.Color.black);

        jCheckBox1.setForeground(java.awt.Color.black);
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Test English - Vietnamese");

        jCheckBox2.setForeground(java.awt.Color.black);
        jCheckBox2.setSelected(true);
        jCheckBox2.setText("Test Vietnamese - English");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setForeground(java.awt.Color.black);
        jCheckBox3.setSelected(true);
        jCheckBox3.setText("Test English Pronunciation - Vietnamese");

        jCheckBox4.setForeground(java.awt.Color.black);
        jCheckBox4.setSelected(true);
        jCheckBox4.setText("Test Vietnamese - English Pronunciation");

        jCheckBox5.setForeground(java.awt.Color.black);
        jCheckBox5.setSelected(true);
        jCheckBox5.setText("Translate Vietnamese - English");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        jCheckBox6.setForeground(java.awt.Color.black);
        jCheckBox6.setSelected(true);
        jCheckBox6.setText("Translate Englisth Pronunciation - English");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox6)
                .addContainerGap())
        );

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, startPanelLayout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(jLabel1))
                        .addGroup(startPanelLayout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(startPanelLayout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nQuesInput)))
                                .addComponent(jLabel2))))
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(nQuesInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        parentPanel0.add(startPanel, "card2");

        processPanel.setForeground(java.awt.Color.black);

        jProgressBar1.setForeground(java.awt.Color.black);

        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("Progress  :");

        progressLabel.setForeground(java.awt.Color.black);

        parentPanel1.setForeground(java.awt.Color.black);
        parentPanel1.setLayout(new java.awt.CardLayout());

        testEngViePanel.setForeground(java.awt.Color.black);
        parentPanel1.add(testEngViePanel, "card3");

        testVieEngPanel.setForeground(java.awt.Color.black);
        parentPanel1.add(testVieEngPanel, "card3");

        testPronunViePanel.setForeground(java.awt.Color.black);
        parentPanel1.add(testPronunViePanel, "card4");

        testViePronunPanel.setForeground(java.awt.Color.black);
        parentPanel1.add(testViePronunPanel, "card5");
        parentPanel1.add(examTranslateVieEngPanel, "card6");
        parentPanel1.add(examTranslatePronunEngPanel, "card7");

        nextButton.setBackground(java.awt.Color.white);
        nextButton.setForeground(java.awt.Color.black);
        nextButton.setText("Next ");
        nextButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nextButton.setContentAreaFilled(false);
        nextButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        nextButton.setOpaque(true);
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonPress(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRelease(evt);
            }
        });
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        jLabel3.setBackground(java.awt.Color.white);
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("Question");

        curQuesLabel.setBackground(java.awt.Color.white);
        curQuesLabel.setForeground(java.awt.Color.black);

        jPanel2.setForeground(java.awt.Color.black);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout processPanelLayout = new javax.swing.GroupLayout(processPanel);
        processPanel.setLayout(processPanelLayout);
        processPanelLayout.setHorizontalGroup(
            processPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(processPanelLayout.createSequentialGroup()
                .addGroup(processPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(processPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(curQuesLabel))
                    .addGroup(processPanelLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addGroup(processPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(processPanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(progressLabel)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, processPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(processPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(249, 249, 249))
        );
        processPanelLayout.setVerticalGroup(
            processPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(processPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(progressLabel)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(processPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(curQuesLabel))
                .addGap(18, 18, 18)
                .addComponent(parentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        parentPanel0.add(processPanel, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parentPanel0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nQuesInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nQuesInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nQuesInputActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        try {
            nQuestions = new Integer(nQuesInput.getText());
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Number of questions is not valid", "Error message", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (nQuestions <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Number of questions is not valid", "Error message", javax.swing.JOptionPane.ERROR_MESSAGE);            
            return;
        }
        
        if (! updateChoosen())
            return;

        parentPanel0.removeAll();
        parentPanel0.add(processPanel);
        parentPanel0.repaint();
        parentPanel0.revalidate();

        curQues = 1;
        jProgressBar1.setMaximum(nQuestions);
        Point.getInstance().resetPoint();
        runTest();
    }//GEN-LAST:event_startButtonActionPerformed

    private boolean updateChoosen() {
        boolean error = true;
        for (int i = 0; i < 6; i++) {
            if (listCheckBox.get(i).isSelected()) {
                choosen[i] = 1;
                error = false;
            } else
                choosen[i] = 0;
        }
        if (error) {
            javax.swing.JOptionPane.showMessageDialog(this, "You must choose at least one format of question.", "Error message", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        return ! error;
    }
    
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        if (curQues == nQuestions + 1) {
            int point = Point.getInstance().getPoint();
            String msg = String.format("Your result: %d / %d%n", point, nQuestions);
            if ((double)point / nQuestions <= 0.4) 
                msg += "Your should study English harder!!!";
            else if ((double)point / nQuestions >= 0.8)
                msg += "Impressionary, your English very good.";
            else
                msg += "Good test.";
            javax.swing.JOptionPane.showMessageDialog(this, msg, "Result", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            parentPanel0.removeAll();
            parentPanel0.add(startPanel);
            parentPanel0.repaint();
            parentPanel0.revalidate();
            
            return;
        }
        runTest();
    }//GEN-LAST:event_nextButtonActionPerformed

    private void buttonPress(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPress
        SwingUtil.buttonClick(evt);
    }//GEN-LAST:event_buttonPress

    private void buttonRelease(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRelease
        SwingUtil.buttonRelease(evt);
    }//GEN-LAST:event_buttonRelease

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void runTest() {
        progressLabel.setText(String.format("%d / %d", curQues, nQuestions));
        jProgressBar1.setValue(curQues);
        curQuesLabel.setText(String.format("%d", curQues));
        
        int index = 0;
        do {
            index = SwingUtil.randomMachine.nextInt(listFormatTest.size());
        } while (choosen[index] == 0);
        AbstractPanel choosenFormat = listFormatTest.get(index);
        parentPanel1.removeAll();
        parentPanel1.add(choosenFormat);
        parentPanel1.repaint();
        parentPanel1.revalidate();
        choosenFormat.loadQuestion();
        
        curQues++;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel curQuesLabel;
    private graphic.ExamTranslatePronunEngPanel examTranslatePronunEngPanel;
    private graphic.ExamTranslateVieEngPanel examTranslateVieEngPanel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JTextField nQuesInput;
    private javax.swing.JButton nextButton;
    private javax.swing.JPanel parentPanel0;
    private javax.swing.JPanel parentPanel1;
    private javax.swing.JPanel processPanel;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel startPanel;
    private graphic.TestEngViePanel testEngViePanel;
    private graphic.TestPronunViePanel testPronunViePanel;
    private graphic.TestVieEngPanel testVieEngPanel;
    private graphic.TestViePronunPanel testViePronunPanel;
    // End of variables declaration//GEN-END:variables
}
