package graphic;

import java.util.Scanner;

public class StatisticPanel extends javax.swing.JPanel {

    /**
     * Creates new form StatisticPanel
     */
    public StatisticPanel() {
        initComponents();
        additionInit();
    }
    
    private void additionInit() {
        delButton.setIcon(new javax.swing.ImageIcon("icon/icons8-clear-symbol-20.png"));
        clearButton.setIcon(new javax.swing.ImageIcon("icon/icons8-delete-bin-20.png"));
        iconLabel.setIcon(new javax.swing.ImageIcon("icon/icons8-filter-20.png"));
    }
    
    public void updateHistory() {
        SwingUtil.dict.sts.setWidth(-24);
        if (filterBox.getSelectedIndex() == 0)
            displayAllWords();
        else if (filterBox.getSelectedIndex() == 2)
            displayOldestWords();
        else
            displayTodayWords();
    }
    
    private void displayAllWords() {
        historyList.setListData(SwingUtil.dict.sts.allLearnedWord());
        totalLabel.setText(String.format("Total : %3d word(s)", SwingUtil.dict.sts.allLearnedWord().length));
    }
    
    private void displayOldestWords() {
        historyList.setListData(SwingUtil.dict.sts.oldestWord(10));
        totalLabel.setText(String.format("Total : %3d word(s)", SwingUtil.dict.sts.oldestWord(10).length));
    }
    
    private void displayTodayWords() {
        historyList.setListData(SwingUtil.dict.sts.wordSearchToday());
        totalLabel.setText(String.format("Total : %3d word(s)", SwingUtil.dict.sts.wordSearchToday().length));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        historyList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        filterBox = new javax.swing.JComboBox<>();
        clearButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        delButton = new javax.swing.JButton();
        iconLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane1.setViewportView(historyList);

        jLabel1.setText("History");

        jLabel2.setText("Word");

        jLabel3.setText("Date");

        filterBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All words", "Words learned today", "10 words oldest" }));
        filterBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filterBoxItemStateChanged(evt);
            }
        });

        clearButton.setBackground(java.awt.Color.white);
        clearButton.setForeground(java.awt.Color.black);
        clearButton.setText(" Clear all ");
        clearButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        clearButton.setContentAreaFilled(false);
        clearButton.setOpaque(true);
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonPress(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRelease(evt);
            }
        });
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Filter :");

        delButton.setBackground(java.awt.Color.white);
        delButton.setForeground(java.awt.Color.black);
        delButton.setText("Delete word");
        delButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        delButton.setContentAreaFilled(false);
        delButton.setOpaque(true);
        delButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                delButtonbuttonPress(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                delButtonbuttonRelease(evt);
            }
        });
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel2)
                        .addGap(164, 164, 164)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(filterBox, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(totalLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(filterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(iconLabel)
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(delButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalLabel)
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        SwingUtil.dict.his.clear();
        displayAllWords();
        javax.swing.JOptionPane.showMessageDialog(this, "Delete history successfully");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void buttonPress(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonPress
        SwingUtil.buttonClick(evt);
    }//GEN-LAST:event_buttonPress

    private void buttonRelease(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRelease
        SwingUtil.buttonRelease(evt);
    }//GEN-LAST:event_buttonRelease

    private void filterBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filterBoxItemStateChanged
        updateHistory();
    }//GEN-LAST:event_filterBoxItemStateChanged

    private void delButtonbuttonPress(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delButtonbuttonPress
        SwingUtil.buttonClick(evt);
    }//GEN-LAST:event_delButtonbuttonPress

    private void delButtonbuttonRelease(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delButtonbuttonRelease
        SwingUtil.buttonRelease(evt);
    }//GEN-LAST:event_delButtonbuttonRelease

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        if (historyList.getSelectedValue() != null) {
            int tmp = historyList.getSelectedIndex();
            Scanner split = new Scanner(historyList.getSelectedValue());
            SwingUtil.dict.his.deleteWord(split.next());
            updateHistory();
            if (tmp == historyList.getModel().getSize())
                tmp--;
            historyList.setSelectedIndex(tmp);
        }
    }//GEN-LAST:event_delButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton delButton;
    private javax.swing.JComboBox<String> filterBox;
    private javax.swing.JList<String> historyList;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
