
package graphic;

import core.Vocabulary;
import core.Meaning;
import java.io.File;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Scanner;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

public class TranslatePanel extends javax.swing.JPanel {
    /**
     * Creates new form TranslatePanel
     */
    public TranslatePanel() {
        SwingUtil.setUIFont(SwingUtil.defaultFont);
        initComponents();
        additionInit();
    }
    
    private void additionInit() {
        searchBox.setUI(new javax.swing.plaf.basic.BasicComboBoxUI() {
            @Override
            protected javax.swing.JButton createArrowButton() {
                return new javax.swing.JButton() {
                    @Override
                    public int getWidth() {
                        return 0;
                    }
                };
            }
        });
        AutoCompleteDecorator.decorate(searchBox);
        jLabel4.setText("<html>Illustrative<br>Image</html>");
        updateSearchHistory();
        searchButton.setIcon(new javax.swing.ImageIcon("icon/icons8-search-24.png"));
    }
    
    void updateSearchBox() {
        searchBox.removeAllItems();
        HashSet<String> exist = new HashSet<>();
        for (String s: SwingUtil.dict.vMng.getListKey()) {
            if (exist.contains(s))
                continue;
            exist.add(s);
            searchBox.addItem(s);
        }
        searchBox.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchButton = new javax.swing.JButton();
        resPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        searchRes = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        foundIn = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchHistory = new javax.swing.JList<>();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        searchButton.setBackground(java.awt.Color.white);
        searchButton.setForeground(java.awt.Color.black);
        searchButton.setText("Search");
        searchButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchButton.setContentAreaFilled(false);
        searchButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        searchButton.setOpaque(true);
        searchButton.setPreferredSize(new java.awt.Dimension(54, 24));
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonClick(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                buttonRelease(evt);
            }
        });
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        resPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        searchRes.setEditable(false);
        searchRes.setColumns(20);
        searchRes.setLineWrap(true);
        searchRes.setRows(5);
        jScrollPane4.setViewportView(searchRes);

        jLabel4.setText("     ");

        javax.swing.GroupLayout resPanelLayout = new javax.swing.GroupLayout(resPanel);
        resPanel.setLayout(resPanelLayout);
        resPanelLayout.setHorizontalGroup(
            resPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4)
            .addGroup(resPanelLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        resPanelLayout.setVerticalGroup(
            resPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(resPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resPanelLayout.createSequentialGroup()
                        .addGap(0, 24, Short.MAX_VALUE)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(resPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jLabel1.setText("Found in Vocabularies");

        jLabel2.setText("Result");

        searchBox.setEditable(true);
        searchBox.setSelectedItem(null);
        searchBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        searchBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                searchBoxItemStateChanged(evt);
            }
        });

        foundIn.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                changeCurRes(evt);
            }
        });
        jScrollPane1.setViewportView(foundIn);

        jLabel3.setText("History Search");

        searchHistory.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                searchNewWord(evt);
            }
        });
        jScrollPane2.setViewportView(searchHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchBox, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane2))
                    .addComponent(resPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        String key = (String)searchBox.getSelectedItem();
        if (key != null)
            searchWord(key);
    }//GEN-LAST:event_searchButtonActionPerformed

    void searchWord(String key) {
        String res = "";
        javax.swing.ImageIcon icon = null;
        ArrayList<String> tmp = new ArrayList<>();
        for (Object[] o: SwingUtil.dict.rfc.searchWord(key)) {
            Meaning m = (Meaning)o[0];
            Vocabulary v = (Vocabulary)o[1];
            tmp.add(v.getName());
            res += String.format("FROM %-15s%n%n%n    %-15s%n%n        %-15s%n%n%n%n", v.getName().toUpperCase(), m.getPronunciation(), m.getMean());
        
            for (String dir: v.gerImageDir()) {
                String imgPath = dir + "/" + key + ".jpg";
                if (new File(imgPath).exists()) {
                    java.awt.Image rawImg = new javax.swing.ImageIcon(imgPath).getImage();
                    icon = new javax.swing.ImageIcon(rawImg.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), java.awt.Image.SCALE_SMOOTH));
                }
            }
        }
        searchRes.setText(res);
        foundIn.setListData(tmp.toArray(new String[0]));
        imageLabel.setIcon(icon);
        updateSearchHistory();
        foundIn.setSelectedIndex(0);
        searchRes.setCaretPosition(0);
    }
    
    public void updateSearchHistory() {
        SwingUtil.dict.sts.setWidth(-13);
        searchHistory.setListData(SwingUtil.dict.sts.recentWord(30));
    }
    
    private void buttonClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonClick
        SwingUtil.buttonClick(evt);
    }//GEN-LAST:event_buttonClick

    private void buttonRelease(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRelease
        SwingUtil.buttonRelease(evt);
    }//GEN-LAST:event_buttonRelease

    private void changeCurRes(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_changeCurRes
        int line = foundIn.getSelectedIndex() * 155;
        searchRes.scrollRectToVisible(new java.awt.Rectangle(0, line, 293, 155));
    }//GEN-LAST:event_changeCurRes

    private void searchNewWord(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_searchNewWord
        try {
            Scanner his = new Scanner(searchHistory.getSelectedValue());
            String key = his.next();
            searchWord(key);
            searchBox.setSelectedItem(key);
        } catch (Exception e) {}
    }//GEN-LAST:event_searchNewWord

    private void searchBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_searchBoxItemStateChanged
//        String key = (String)searchBox.getSelectedItem();
//        if (key != null)
//            searchWord(key);
    }//GEN-LAST:event_searchBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> foundIn;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel resPanel;
    private javax.swing.JComboBox<String> searchBox;
    private javax.swing.JButton searchButton;
    private javax.swing.JList<String> searchHistory;
    private javax.swing.JTextArea searchRes;
    // End of variables declaration//GEN-END:variables
}
